data-sweeper:
    scale: 1
    startup: yes
    always: yes
    network: NodePort
    ports:
      - name: data-sweeper
        protocol: TCP
        port: xxxx
        nodePort: xxxx
    env:
      TZ: Asia/Tokyo
      MYSQL_USER: "xxxx"
      MYSQL_PASSWORD: "xxxx"
      MYSQL_SERVICE_HOST: "mysql"
      MYSQL_SERVICE_PORT: "xxxx"
      MYSQL_DB_NAME: "xxxx"
    volumeMountPathList:
      # Aion上でVolumeをマウントする場合、k8s上でボリュームを指定する場合と異なり、volumeMountsのパス:volumeのパスという書き方をする。
      # volumeには、data-sweeper-kube.yaml が配置されている場所を指定する。デフォルトでの配置場所は/var/lib/aion/default/configになっています。
      - /var/lib/aion/config:/var/lib/aion/default/config