# DATA SWEEPER
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    run: data-sweeper
  name: data-sweeper
spec:
  replicas: 1
  selector:
    matchLabels:
      run: data-sweeper
  template:
    metadata:
      labels:
        run: data-sweeper
    spec:
      hostname: data-sweeper
      containers:
      - image: latonaio/data-sweeper:latest
        name: data-sweeper
        env:
        - name: TZ
          value: Asia/Tokyo
        - name: SWEEP_CHECK_INTERVAL
          value: "3000"
        ports:
        - containerPort: 500
          protocol: TCP
        imagePullPolicy: IfNotPresent
        resources: {}
        volumeMounts:
        - name: data
          mountPath: /var/lib/aion/Data
        - name: config
          mountPath: /var/lib/aion/config
      volumes:
      - name: data
        hostPath:
          path: /var/lib/aion/default/Data
      - name: config
        hostPath:
          path: /var/lib/aion/default/config
status: {}

